WebStockPredict/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("stock_predict/",include('stock_predict.urls')),
]

stock_predict/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "stock_predict"

urlpatterns = [
    path("home/",views.home,name='home'),
    path("predict/",views.predict_stock_action,name='predict'),
]

stock_predict/models.py
import json

from django.db import models


# Create your models here.
class Company(models.Model):
    stock_code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)

class StockIndex(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    ri_qi = models.CharField(max_length=30)
    zi_jin = models.IntegerField(default=0)
    qiang_du = models.IntegerField(default=0)
    feng_xian = models.IntegerField(default=0)
    zhuan_qiang = models.IntegerField(default=0)
    chang_yu = models.IntegerField(default=0)
    jin_zi = models.IntegerField(default=0)
    zong_he = models.IntegerField(default=0)


class HistoryData(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    data = models.TextField() # 字符串类型
    start_date = models.CharField(max_length=30)

    def set_data(self,list_data):   # 将list类型数据，转为字符串存储
        try:
            start_da = list_data[0][0]  # 记录第一条数据的日期
            data_json = json.dumps(list_data)  # 可以将list或dict类型 转为字符串
        except (KeyError,TypeError,IndexError):
            raise Exception("list_data must be 2 dimensions list.")
        else:
            self.start_date = start_da
            self.data = data_json

    def get_data(self):
        return json.loads(self.data)        # 可以将字符串 转为list或dict类型

class PredictData(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    data = models.TextField()  # 字符串类型
    start_date = models.CharField(max_length=30)

    def set_data(self, list_data):  # 将list类型数据，转为字符串存储
        try:
            st_da = list_data[0][0]  # 记录第一条数据的日期
            data_json = json.dumps(list_data)  # 可以将list或dict类型 转为字符串
        except (KeyError,TypeError):
            raise Exception("list_data must be 2 dimensions list.")
        else:
            self.start_date = st_da
            self.data = data_json

    def get_data(self):
        return json.loads(self.data)  # 可以将字符串 转为list或dict类型

stock_predict/views.py
import json
import os

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from LSTMPredictStock import run
from stock_predict import models
from datetime import datetime as dt
from apscheduler.scheduler import Scheduler
from .models import Company

import pandas as pd

LOCAL = False

def get_hist_predict_data(stock_code):
    recent_data,predict_data = None,None
    # company = models.Company.objects.get(stock_code=stock_code)
    company = get_object_or_404(Company, stock_code=stock_code)

    if company.historydata_set.count() <= 0:
        history_data = models.HistoryData()
        history_data.company = company
        history_data.set_data(run.get_hist_data(stock_code=stock_code,recent_day=20))
        history_data.save()
        recent_data = history_data.get_data()
    else:
        all_data = company.historydata_set.all()
        for single in all_data:
            now = dt.now()
            end_date = single.get_data()[-1][0]
            end_date = dt.strptime(end_date,"%Y-%m-%d")
            if LOCAL & (now.date() > end_date.date()):        # 更新预测数据
                single.set_data(run.get_hist_data(stock_code=stock_code,recent_day=20))
                single.save()

            recent_data = single.get_data()
            break

    if company.predictdata_set.count() <= 0:
        predict_data = models.PredictData()
        predict_data.company = company
        predict_data.set_data(run.prediction(stock_code,pre_len=10))
        predict_data.save()
        predict_data = predict_data.get_data()
    else:
        all_data = company.predictdata_set.all()
        for single in all_data:
            now = dt.now()
            start_date = dt.strptime(single.start_date,"%Y-%m-%d")
            if LOCAL & (now.date() > start_date.date()):  # 更新预测数据
                single.set_data(run.prediction(stock_code, pre_len=10))
                single.save()

            predict_data = single.get_data()
            break

    return recent_data,predict_data

def get_crawl_save_data():
    """
    将10个公司的指标数据爬取并保存到数据库
    """
    # 此处应是从网上爬取数据，并保存为csv文件
    parent_dir = os.path.dirname(__file__)  # "stock_predict/views.py"
    file_dir = os.path.join(parent_dir, "stock_index/")
    for file_name in os.listdir(file_dir):
        file_path =  os.path.join(file_dir, file_name)
        data_frame = pd.read_csv(file_path)
        stock_code = file_name.split('.')[0]
        company = get_object_or_404(Company, stock_code=stock_code)
        for index,row in data_frame.iterrows():
            company.stockindex_set.create(ri_qi=row['ri_qi'],zi_jin=row['zi_jin'],qiang_du=row['qiang_du'],feng_xian=row['feng_xian'],
                zhuan_qiang=row['zhuan_qiang'],chang_yu=row['chang_yu'],jin_zi=row['jin_zi'],zong_he=row['zong_he'])

def get_stock_index(stock_code):
    """
    获取股票的各项指标数据
    """
    company = get_object_or_404(Company, stock_code=stock_code)
    if company.stockindex_set.count() <= 0:
        # 将爬取的数据存入数据库
        get_crawl_save_data()
    # 从数据库获取近三天的数据
    indexs = company.stockindex_set.all().order_by('-ri_qi')[:3].values()
    return list(indexs)


def home(request):
    recent_data,predict_data = get_hist_predict_data("600718")
    data = {"recent_data":recent_data,"stock_code":"600718","predict_data":predict_data}
    data['indexs'] = get_stock_index("600718")
    return render(request,"stock_predict/home.html",{"data":json.dumps(data)}) # json.dumps(list)

def predict_stock_action(request):
    stock_code = request.POST.get('stock_code',None)
    # print("stock_code:\n",stock_code)
    recent_data, predict_data = get_hist_predict_data(stock_code)
    data = {"recent_data": recent_data, "stock_code": stock_code, "predict_data": predict_data}
    data['indexs'] = get_stock_index(stock_code)
    return render(request, "stock_predict/home.html", {"data": json.dumps(data)})  # json.dumps(list)

sched = Scheduler()
# 定时任务
# @sched.interval_schedule(seconds=2)   # 每2s执行一次
@sched.cron_schedule(hour=0,minute=0)   # 每日凌晨调度一次
def train_models():
    run.train_all_stock()

sched.start()

stock_predict/templates/stock_predict/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>股票预测系统</title>
    {% load static %}
    <script src="{% static 'stock_predict/js/echarts.min.js' %}"></script>
</head>
<body>
<script type="text/javascript">
        var stock_data = null
        {% if data %}
            stock_data = {{data|safe}};
            var recent_data = stock_data['recent_data'];
            var stock_code = stock_data['stock_code'];
            var predict_data = stock_data['predict_data'];
            var indexs = null;
            indexs = stock_data['indexs']
        {% endif %}
        console.log(stock_data);
</script>
<center>
    <h1>股票预测系统</h1>
    <div style="position:center;margin-top: 50px">
        <form id="commit_stock_code" action="{% url 'stock_predict:predict' %}" method="post">
            {% csrf_token %}
            <select name="stock_code" style="width: 200px; text-align: center; padding:5px;">
                <option id="600718" value="600718">东软集团(600718)</option>
                <option id="000651" value="000651">格力电器(000651)</option>
                <option id="600839" value="600839">四川长虹(600839)</option>
                <option id="600320" value="600320">振华重工(600320)</option>
                <option id="601988" value="601988">中国银行(601988)</option>
                <option id="000066" value="000066">中国长城(000066)</option>
                <option id="601766" value="601766">中国中车(601766)</option>
                <option id="601390" value="601390">中国中铁(601390)</option>
                <option id="000768" value="000768">中航飞机(000768)</option>
                <option id="000063" value="000063">中兴通讯(000063)</option>
            </select>
            <input type="submit" value="查询" style="padding:5px;">
        </form>
    </div>
    <!-- 为ECharts准备一个具备大小（宽高）的容器 -->
    <div style="width:100%;height:400px;margin-top:50px;">
        <div id="hist_futu" style="float:left;width: 100%;height:450px;"></div>
        <div id="radar" style="width:50%;height:600px;"></div>
    </div>
</center>
<script src="{% static 'stock_predict/js/draw_charts.js' %}"></script>
</body>
</html>